<?php

use Illuminate\Database\Seeder;

class FAMParameterTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('FAM_Parameter')->delete();
        
        \DB::table('FAM_Parameter')->insert(array(
            0 =>
            array(
                'id' => 41,
                'stage_id' => 3,
                'category_id' => 6,
                'name' => 'Knowledge about MAD',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            1 =>
            array(
                'id' => 42,
                'stage_id' => 3,
                'category_id' => 6,
                'name' => 'Creativity',
                'type' => '1-5',
                'required' => '1',
                'sort' => 50,
                'status' => '0',
            ),
            2 =>
            array(
                'id' => 43,
                'stage_id' => 3,
                'category_id' => 6,
                'name' => 'Presence',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            3 =>
            array(
                'id' => 44,
                'stage_id' => 3,
                'category_id' => 6,
                'name' => 'Confidence',
                'type' => '1-5',
                'required' => '1',
                'sort' => 40,
                'status' => '0',
            ),
            4 =>
            array(
                'id' => 45,
                'stage_id' => 3,
                'category_id' => 6,
                'name' => 'Inspiring',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            5 =>
            array(
                'id' => 46,
                'stage_id' => 3,
                'category_id' => 7,
                'name' => 'Good Perspective',
                'type' => '1-5',
                'required' => '1',
                'sort' => 0,
                'status' => '0',
            ),
            6 =>
            array(
                'id' => 47,
                'stage_id' => 3,
                'category_id' => 7,
                'name' => 'Positivity',
                'type' => '1-5',
                'required' => '1',
                'sort' => 0,
                'status' => '0',
            ),
            7 =>
            array(
                'id' => 48,
                'stage_id' => 3,
                'category_id' => 7,
                'name' => 'Clarity of Thought',
                'type' => '1-5',
                'required' => '1',
                'sort' => 0,
                'status' => '0',
            ),
            8 =>
            array(
                'id' => 49,
                'stage_id' => 3,
                'category_id' => 8,
                'name' => 'Comments',
                'type' => 'text',
                'required' => '1',
                'sort' => 0,
                'status' => '0',
            ),
            9 =>
            array(
                'id' => 50,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Present at the beginning of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            10 =>
            array(
                'id' => 51,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Present at the end of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            11 =>
            array(
                'id' => 52,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Informed if late/not attending',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            12 =>
            array(
                'id' => 53,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Shared act of kindness on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            13 =>
            array(
                'id' => 54,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Uploaded share on google doc',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 50,
                'status' => '1',
            ),
            14 =>
            array(
                'id' => 55,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Has shared reflections/learnings.',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 60,
                'status' => '1',
            ),
            15 =>
            array(
                'id' => 56,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Engaged with others in group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 70,
                'status' => '1',
            ),
            16 =>
            array(
                'id' => 57,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Has initiated conversations on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 80,
                'status' => '1',
            ),
            17 =>
            array(
                'id' => 58,
                'stage_id' => 1,
                'category_id' => 1,
                'name' => 'Any other observations/comments',
                'type' => 'text',
                'required' => '1',
                'sort' => 90,
                'status' => '1',
            ),
            18 =>
            array(
                'id' => 59,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Present at the beginning of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            19 =>
            array(
                'id' => 60,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Present at the end of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            20 =>
            array(
                'id' => 61,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Informed if late/not attending',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            21 =>
            array(
                'id' => 62,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Shared act of kindness on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            22 =>
            array(
                'id' => 63,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Uploaded share on google doc',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 50,
                'status' => '1',
            ),
            23 =>
            array(
                'id' => 64,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Has shared reflections/learnings.',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 60,
                'status' => '1',
            ),
            24 =>
            array(
                'id' => 65,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Engaged with others in group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 70,
                'status' => '1',
            ),
            25 =>
            array(
                'id' => 66,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Has initiated conversations on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 80,
                'status' => '1',
            ),
            26 =>
            array(
                'id' => 67,
                'stage_id' => 1,
                'category_id' => 2,
                'name' => 'Any other observations/comments',
                'type' => 'text',
                'required' => '1',
                'sort' => 90,
                'status' => '1',
            ),
            27 =>
            array(
                'id' => 68,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Present at the beginning of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            28 =>
            array(
                'id' => 69,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Present at the end of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            29 =>
            array(
                'id' => 70,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Informed if late/not attending',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            30 =>
            array(
                'id' => 71,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Shared act of kindness on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            31 =>
            array(
                'id' => 72,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Uploaded share on google doc',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 50,
                'status' => '1',
            ),
            32 =>
            array(
                'id' => 73,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Has shared reflections/learnings.',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 60,
                'status' => '1',
            ),
            33 =>
            array(
                'id' => 74,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Engaged with others in group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 70,
                'status' => '1',
            ),
            34 =>
            array(
                'id' => 75,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Has initiated conversations on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 80,
                'status' => '1',
            ),
            35 =>
            array(
                'id' => 76,
                'stage_id' => 1,
                'category_id' => 3,
                'name' => 'Any other observations/comments',
                'type' => 'text',
                'required' => '1',
                'sort' => 90,
                'status' => '1',
            ),
            36 =>
            array(
                'id' => 77,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Present at the beginning of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            37 =>
            array(
                'id' => 78,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Present at the end of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            38 =>
            array(
                'id' => 79,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Informed if late/not attending',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            39 =>
            array(
                'id' => 80,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Shared act of kindness on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            40 =>
            array(
                'id' => 81,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Uploaded share on google doc',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 50,
                'status' => '1',
            ),
            41 =>
            array(
                'id' => 82,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Has shared reflections/learnings.',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 60,
                'status' => '1',
            ),
            42 =>
            array(
                'id' => 83,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Engaged with others in group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 70,
                'status' => '1',
            ),
            43 =>
            array(
                'id' => 84,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Has initiated conversations on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 80,
                'status' => '1',
            ),
            44 =>
            array(
                'id' => 85,
                'stage_id' => 1,
                'category_id' => 4,
                'name' => 'Any other observations/comments',
                'type' => 'text',
                'required' => '1',
                'sort' => 90,
                'status' => '1',
            ),
            45 =>
            array(
                'id' => 86,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Present at the beginning of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            46 =>
            array(
                'id' => 87,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Present at the end of the activity',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            47 =>
            array(
                'id' => 88,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Informed if late/not attending',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            48 =>
            array(
                'id' => 89,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Shared act of kindness on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            49 =>
            array(
                'id' => 90,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Uploaded share on google doc',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 50,
                'status' => '1',
            ),
            50 =>
            array(
                'id' => 91,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Has shared reflections/learnings.',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 60,
                'status' => '1',
            ),
            51 =>
            array(
                'id' => 92,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Engaged with others in group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 70,
                'status' => '1',
            ),
            52 =>
            array(
                'id' => 93,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Has initiated conversations on the group',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 80,
                'status' => '1',
            ),
            53 =>
            array(
                'id' => 94,
                'stage_id' => 1,
                'category_id' => 5,
                'name' => 'Any other observations/comments',
                'type' => 'text',
                'required' => '1',
                'sort' => 90,
                'status' => '1',
            ),
            54 =>
            array(
                'id' => 98,
                'stage_id' => 5,
                'category_id' => 11,
                'name' => 'Understanding/Real world modelling of the project',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '0',
            ),
            55 =>
            array(
                'id' => 99,
                'stage_id' => 5,
                'category_id' => 11,
                'name' => 'Ideation and Creativity
',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            56 =>
            array(
                'id' => 100,
                'stage_id' => 5,
                'category_id' => 11,
                'name' => 'Presentation, confidence and pitching skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '0',
            ),
            57 =>
            array(
                'id' => 101,
                'stage_id' => 5,
                'category_id' => 12,
                'name' => 'Story Quality',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '0',
            ),
            58 =>
            array(
                'id' => 102,
                'stage_id' => 5,
                'category_id' => 12,
                'name' => 'Story Document presentation, confidence and pitching skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '0',
            ),
            59 =>
            array(
                'id' => 103,
                'stage_id' => 5,
                'category_id' => 13,
                'name' => 'Critical Thinking',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            60 =>
            array(
                'id' => 104,
                'stage_id' => 5,
                'category_id' => 13,
                'name' => 'Communication skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '0',
            ),
            61 =>
            array(
                'id' => 105,
                'stage_id' => 5,
                'category_id' => 13,
                'name' => 'Mobilisation skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            62 =>
            array(
                'id' => 106,
                'stage_id' => 5,
                'category_id' => 13,
                'name' => 'Interpersonal Skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 40,
                'status' => '0',
            ),
            63 =>
            array(
                'id' => 107,
                'stage_id' => 5,
                'category_id' => 14,
                'name' => 'Collaborative / Aligner',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            64 =>
            array(
                'id' => 108,
                'stage_id' => 5,
                'category_id' => 14,
            'name' => 'Logical (Critical) thinking / Perspective',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            65 =>
            array(
                'id' => 109,
                'stage_id' => 5,
                'category_id' => 14,
                'name' => 'Upward Management',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            66 =>
            array(
                'id' => 110,
                'stage_id' => 4,
                'category_id' => 15,
                'name' => 'Communication Skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            67 =>
            array(
                'id' => 111,
                'stage_id' => 4,
                'category_id' => 15,
                'name' => 'Patience and thinking on feet',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            68 =>
            array(
                'id' => 113,
                'stage_id' => 5,
                'category_id' => 16,
                'name' => 'Critical Thinking',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            69 =>
            array(
                'id' => 114,
                'stage_id' => 5,
                'category_id' => 16,
                'name' => 'Prioritization',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            70 =>
            array(
                'id' => 115,
                'stage_id' => 5,
                'category_id' => 16,
                'name' => 'Emotional Maturity',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            71 =>
            array(
                'id' => 116,
                'stage_id' => 5,
                'category_id' => 16,
                'name' => 'Child connect/Ability to understand child perspective',
                'type' => '1-5',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            72 =>
            array(
                'id' => 117,
                'stage_id' => 5,
                'category_id' => 17,
                'name' => 'Mobilization',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            73 =>
            array(
                'id' => 118,
                'stage_id' => 5,
                'category_id' => 28,
                'name' => 'Able to work with MADapp data',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            74 =>
            array(
                'id' => 119,
                'stage_id' => 5,
                'category_id' => 28,
                'name' => 'Work in a team and is Resourceful',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            75 =>
            array(
                'id' => 120,
                'stage_id' => 5,
                'category_id' => 28,
                'name' => 'Comes from a space of Empowerment',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            76 =>
            array(
                'id' => 121,
                'stage_id' => 5,
                'category_id' => 18,
                'name' => 'Mobilizer',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '0',
            ),
            77 =>
            array(
                'id' => 122,
                'stage_id' => 5,
                'category_id' => 18,
                'name' => 'Planning',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '0',
            ),
            78 =>
            array(
                'id' => 123,
                'stage_id' => 5,
                'category_id' => 18,
                'name' => 'Creativity',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '0',
            ),
            79 =>
            array(
                'id' => 124,
                'stage_id' => 5,
                'category_id' => 19,
                'name' => 'Finance Orientation',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            80 =>
            array(
                'id' => 125,
                'stage_id' => 5,
                'category_id' => 19,
                'name' => 'Critical Thinking',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            81 =>
            array(
                'id' => 126,
                'stage_id' => 5,
                'category_id' => 19,
                'name' => 'Team Player',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            82 =>
            array(
                'id' => 127,
                'stage_id' => 5,
                'category_id' => 19,
                'name' => 'Self-Starter',
                'type' => '1-5',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            83 =>
            array(
                'id' => 128,
                'stage_id' => 5,
                'category_id' => 21,
                'name' => 'Critical Thinking',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '0',
            ),
            84 =>
            array(
                'id' => 129,
                'stage_id' => 5,
                'category_id' => 21,
                'name' => 'Communication skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '0',
            ),
            85 =>
            array(
                'id' => 130,
                'stage_id' => 5,
                'category_id' => 21,
                'name' => 'Mobilisation skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            86 =>
            array(
                'id' => 131,
                'stage_id' => 5,
                'category_id' => 21,
                'name' => 'Interpersonal Skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            87 =>
            array(
                'id' => 132,
                'stage_id' => 5,
                'category_id' => 22,
                'name' => 'Presentation Skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            88 =>
            array(
                'id' => 133,
                'stage_id' => 5,
                'category_id' => 23,
                'name' => 'Entrepreneurial/ self starter potential',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '0',
            ),
            89 =>
            array(
                'id' => 134,
                'stage_id' => 5,
                'category_id' => 23,
                'name' => 'Entrepreneurial/ self starter potential',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '0',
            ),
            90 =>
            array(
                'id' => 135,
                'stage_id' => 5,
                'category_id' => 23,
                'name' => 'Connection of the initiative to the need',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            91 =>
            array(
                'id' => 136,
                'stage_id' => 5,
                'category_id' => 23,
                'name' => 'Impact of the initiative',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            92 =>
            array(
                'id' => 137,
                'stage_id' => 5,
                'category_id' => 24,
                'name' => 'Thrives on uncertainty',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            93 =>
            array(
                'id' => 138,
                'stage_id' => 5,
                'category_id' => 24,
                'name' => 'Enjoys training, mentoring and coaching',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            94 =>
            array(
                'id' => 139,
                'stage_id' => 5,
                'category_id' => 24,
                'name' => 'Visibility to Director',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            95 =>
            array(
                'id' => 140,
                'stage_id' => 5,
                'category_id' => 9,
                'name' => 'Current understanding of the city',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            96 =>
            array(
                'id' => 141,
                'stage_id' => 5,
                'category_id' => 9,
                'name' => 'Ability to strategize for team building',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            97 =>
            array(
                'id' => 142,
                'stage_id' => 5,
                'category_id' => 9,
                'name' => 'Ability to strategize for driving a cohesive, participative culture',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '0',
            ),
            98 =>
            array(
                'id' => 143,
                'stage_id' => 5,
                'category_id' => 9,
                'name' => 'Ability to operationalize/execution of plan',
                'type' => '1-5',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            99 =>
            array(
                'id' => 144,
                'stage_id' => 5,
                'category_id' => 10,
                'name' => 'Inspiring',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            100 =>
            array(
                'id' => 145,
                'stage_id' => 5,
                'category_id' => 10,
                'name' => 'Enthusiasm',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            101 =>
            array(
                'id' => 146,
                'stage_id' => 5,
                'category_id' => 10,
                'name' => 'Presence',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            102 =>
            array(
                'id' => 147,
                'stage_id' => 5,
                'category_id' => 10,
                'name' => 'Confidence',
                'type' => '1-5',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            103 =>
            array(
                'id' => 148,
                'stage_id' => 5,
                'category_id' => 10,
                'name' => 'Creativity',
                'type' => '1-5',
                'required' => '1',
                'sort' => 50,
                'status' => '1',
            ),
            104 =>
            array(
                'id' => 149,
                'stage_id' => 5,
                'category_id' => 10,
                'name' => 'Knowledgeable about MAD',
                'type' => '1-5',
                'required' => '1',
                'sort' => 60,
                'status' => '1',
            ),
            105 =>
            array(
                'id' => 150,
                'stage_id' => 5,
                'category_id' => 26,
                'name' => 'Critical Thinking',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '0',
            ),
            106 =>
            array(
                'id' => 151,
                'stage_id' => 5,
                'category_id' => 26,
                'name' => 'Communication/Facilitation skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            107 =>
            array(
                'id' => 152,
                'stage_id' => 5,
                'category_id' => 26,
                'name' => 'Mobilisation skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '0',
            ),
            108 =>
            array(
                'id' => 153,
                'stage_id' => 5,
                'category_id' => 26,
                'name' => 'Interpersonal Skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            109 =>
            array(
                'id' => 154,
                'stage_id' => 5,
                'category_id' => 26,
                'name' => 'Research & Analysis',
                'type' => '1-5',
                'required' => '1',
                'sort' => 50,
                'status' => '0',
            ),
            110 =>
            array(
                'id' => 155,
                'stage_id' => 3,
                'category_id' => 6,
                'name' => 'Enthusiasm',
                'type' => '1-5',
                'required' => '1',
                'sort' => 22,
                'status' => '1',
            ),
            111 =>
            array(
                'id' => 156,
                'stage_id' => 5,
                'category_id' => 14,
                'name' => 'Clarity of Thought',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            112 =>
            array(
                'id' => 157,
                'stage_id' => 3,
                'category_id' => 6,
                'name' => 'Oral Communication',
                'type' => '1-5',
                'required' => '1',
                'sort' => 50,
                'status' => '1',
            ),
            113 =>
            array(
                'id' => 158,
                'stage_id' => 3,
                'category_id' => 6,
                'name' => 'Proactive',
                'type' => '1-5',
                'required' => '1',
                'sort' => 60,
                'status' => '1',
            ),
            114 =>
            array(
                'id' => 159,
                'stage_id' => 3,
                'category_id' => 7,
            'name' => 'Critical Thinking<br />(Question a and b)',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            115 =>
            array(
                'id' => 160,
                'stage_id' => 3,
                'category_id' => 7,
            'name' => 'Written Communication skills<br />(Question a and b)',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            116 =>
            array(
                'id' => 161,
                'stage_id' => 3,
                'category_id' => 7,
            'name' => 'Empathetic /Mindful of Context/People centric (Cares for people)<br />(Question a and b)',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            117 =>
            array(
                'id' => 162,
                'stage_id' => 3,
                'category_id' => 7,
            'name' => 'Proactive, ownership and drive<br />(Question c)',
                'type' => '1-5',
                'required' => '1',
                'sort' => 40,
                'status' => '1',
            ),
            118 =>
            array(
                'id' => 163,
                'stage_id' => 5,
                'category_id' => 13,
                'name' => 'Empathetic and
non-judgemental',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            119 =>
            array(
                'id' => 164,
                'stage_id' => 5,
                'category_id' => 11,
                'name' => 'Understanding and Planning',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            120 =>
            array(
                'id' => 166,
                'stage_id' => 5,
                'category_id' => 12,
                'name' => 'Volunteer Experience',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            121 =>
            array(
                'id' => 167,
                'stage_id' => 5,
                'category_id' => 9,
                'name' => 'Ability to strategize for a positive volunteer experience',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            122 =>
            array(
                'id' => 168,
                'stage_id' => 5,
                'category_id' => 20,
                'name' => 'Budgetting',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            123 =>
            array(
                'id' => 169,
                'stage_id' => 5,
                'category_id' => 18,
                'name' => 'Understanding and Planning',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            124 =>
            array(
                'id' => 170,
                'stage_id' => 5,
                'category_id' => 18,
                'name' => 'Mobilisation',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            125 =>
            array(
                'id' => 171,
                'stage_id' => 5,
                'category_id' => 27,
                'name' => 'Ideation and creativity',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            126 =>
            array(
                'id' => 172,
                'stage_id' => 5,
                'category_id' => 27,
                'name' => 'Relationship Building',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            127 =>
            array(
                'id' => 173,
                'stage_id' => 5,
                'category_id' => 17,
                'name' => 'Ability to work collaboratively/project manage',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            128 =>
            array(
                'id' => 174,
                'stage_id' => 5,
                'category_id' => 16,
                'name' => 'Creativity/Ability to Innovate',
                'type' => '1-5',
                'required' => '1',
                'sort' => 50,
                'status' => '1',
            ),
            129 =>
            array(
                'id' => 175,
                'stage_id' => 5,
                'category_id' => 21,
                'name' => 'Creativity',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            130 =>
            array(
                'id' => 176,
                'stage_id' => 5,
                'category_id' => 22,
                'name' => 'Analytical Skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            131 =>
            array(
                'id' => 177,
                'stage_id' => 5,
                'category_id' => 22,
                'name' => 'Planning Skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            132 =>
            array(
                'id' => 178,
                'stage_id' => 5,
                'category_id' => 29,
                'name' => 'Teaching Skills',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            133 =>
            array(
                'id' => 179,
                'stage_id' => 5,
                'category_id' => 29,
                'name' => 'Ability to work with children',
                'type' => '1-5',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            134 =>
            array(
                'id' => 180,
                'stage_id' => 5,
                'category_id' => 30,
                'name' => 'Monitoring and Ensuring class quality and consistency',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
            135 =>
            array(
                'id' => 181,
                'stage_id' => 5,
                'category_id' => 30,
                'name' => 'Mobilising volunteers & maintaining batch morale',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 20,
                'status' => '1',
            ),
            136 =>
            array(
                'id' => 182,
                'stage_id' => 5,
                'category_id' => 30,
                'name' => 'Getting feedback from fellows and ensuring team alignment',
                'type' => 'yes-no',
                'required' => '1',
                'sort' => 30,
                'status' => '1',
            ),
            137 =>
            array(
                'id' => 183,
                'stage_id' => 5,
                'category_id' => 26,
                'name' => 'Empathetic and Non-Judgemental',
                'type' => '1-5',
                'required' => '1',
                'sort' => 10,
                'status' => '1',
            ),
        ));
    }
}
