<?php

use Illuminate\Database\Seeder;

class UserTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('User')->delete();
        
        \DB::table('User')->insert(array(
            0 =>
            array(
                'id' => 1,
                'name' => 'Admin',
                'title' => null,
                'email' => 'admin@makeadiff.in',
                'mad_email' => null,
                'phone' => '9887478859',
                'sex' => 'f',
                'password' => null,
                'password_hash' => '$2y$10$B6j3FBfUMYl7TlJHSVlMEe8mtfbUeoZEf0TSkMsIxTkmg6MlGdeTm',
                'auth_token' => null,
                'photo' => null,
                'joined_on' => '2019-10-05 17:17:49',
                'address' => null,
                'bio' => null,
                'facebook_id' => null,
                'verification_status' => null,
                'profile_progress' => 0,
                'source' => 'other',
                'source_other' => null,
                'birthday' => null,
                'job_status' => 'student',
                'edu_institution' => null,
                'company' => null,
                'preferred_day' => 'flexible',
                'applied_role' => null,
                'why_mad' => null,
                'left_on' => null,
                'added_on' => '2019-10-05 17:17:49',
                'updated_on' => '2019-10-05 17:17:49',
                'reason_for_leaving' => null,
                'induction_status' => '0',
                'teacher_training_status' => '0',
                'center_id' => null,
                'city_other' => null,
                'city_id' => 28,
                'subject_id' => null,
                'project_id' => 1,
                'user_type' => 'volunteer',
                'credit' => 3.0,
                'consecutive_credit' => null,
                'admin_credit' => null,
                'campaign' => null,
                'zoho_user_id' => null,
                'status' => '1',
                'app_version' => null,
            ),
            1 =>
            array(
                'id' => 2,
                'name' => 'Data',
                'title' => null,
                'email' => 'data.simulation@makeadiff.in',
                'mad_email' => '',
                'phone' => '9987541087',
                'sex' => 'm',
                'password' => null,
                'password_hash' => '$2y$10$r2ds4gFSwvKZ3LwA9nduIuNdjVGNHldo431MZ1GFjhpfIu8AQJYs.',
                'auth_token' => null,
                'photo' => null,
                'joined_on' => '2019-10-08 11:06:45',
                'address' => '',
                'bio' => null,
                'facebook_id' => null,
                'verification_status' => null,
                'profile_progress' => 0,
                'source' => 'other',
                'source_other' => null,
                'birthday' => null,
                'job_status' => 'student',
                'edu_institution' => null,
                'company' => null,
                'preferred_day' => 'flexible',
                'applied_role' => null,
                'why_mad' => null,
                'left_on' => null,
                'added_on' => '0000-00-00 00:00:00',
                'updated_on' => '0000-00-00 00:00:00',
                'reason_for_leaving' => null,
                'induction_status' => '0',
                'teacher_training_status' => '0',
                'center_id' => null,
                'city_other' => null,
                'city_id' => 28,
                'subject_id' => 0,
                'project_id' => 1,
                'user_type' => 'volunteer',
                'credit' => 3.0,
                'consecutive_credit' => null,
                'admin_credit' => null,
                'campaign' => null,
                'zoho_user_id' => null,
                'status' => '1',
                'app_version' => null,
            ),
            2 =>
            array(
                'id' => 3,
                'name' => 'Forge',
                'title' => null,
                'email' => 'forge.simulation@makeadiff.in',
                'mad_email' => '',
                'phone' => '9987549687',
                'sex' => 'm',
                'password' => null,
                'password_hash' => '$2y$10$H9VyDBicVXPxtPdeHyw39O15cVaTcNbflmwDpYbJ5jqtzNQqxV4j.',
                'auth_token' => null,
                'photo' => null,
                'joined_on' => '2019-10-08 11:07:29',
                'address' => '',
                'bio' => null,
                'facebook_id' => null,
                'verification_status' => null,
                'profile_progress' => 0,
                'source' => 'other',
                'source_other' => null,
                'birthday' => null,
                'job_status' => 'student',
                'edu_institution' => null,
                'company' => null,
                'preferred_day' => 'flexible',
                'applied_role' => null,
                'why_mad' => null,
                'left_on' => null,
                'added_on' => '0000-00-00 00:00:00',
                'updated_on' => '0000-00-00 00:00:00',
                'reason_for_leaving' => null,
                'induction_status' => '0',
                'teacher_training_status' => '0',
                'center_id' => null,
                'city_other' => null,
                'city_id' => 28,
                'subject_id' => 0,
                'project_id' => 1,
                'user_type' => 'volunteer',
                'credit' => 3.0,
                'consecutive_credit' => null,
                'admin_credit' => null,
                'campaign' => null,
                'zoho_user_id' => null,
                'status' => '1',
                'app_version' => null,
            ),
            3 =>
            array(
                'id' => 4,
                'name' => 'Picard',
                'title' => null,
                'email' => 'picard.simulation@makeadiff.in',
                'mad_email' => '',
                'phone' => '9987591687',
                'sex' => 'm',
                'password' => null,
                'password_hash' => '$2y$10$g/92SBE.VZf.C8Ti6EWlDeliylXFQusqvFHXVImCkaHkgh4RRKhvy',
                'auth_token' => null,
                'photo' => null,
                'joined_on' => '2019-10-08 11:08:04',
                'address' => '',
                'bio' => null,
                'facebook_id' => null,
                'verification_status' => null,
                'profile_progress' => 0,
                'source' => 'other',
                'source_other' => null,
                'birthday' => null,
                'job_status' => 'student',
                'edu_institution' => null,
                'company' => null,
                'preferred_day' => 'flexible',
                'applied_role' => null,
                'why_mad' => null,
                'left_on' => null,
                'added_on' => '0000-00-00 00:00:00',
                'updated_on' => '0000-00-00 00:00:00',
                'reason_for_leaving' => null,
                'induction_status' => '0',
                'teacher_training_status' => '0',
                'center_id' => null,
                'city_other' => null,
                'city_id' => 28,
                'subject_id' => null,
                'project_id' => 1,
                'user_type' => 'volunteer',
                'credit' => 3.0,
                'consecutive_credit' => null,
                'admin_credit' => null,
                'campaign' => null,
                'zoho_user_id' => null,
                'status' => '1',
                'app_version' => null,
            ),
            4 =>
            array(
                'id' => 5,
                'name' => 'Riker',
                'title' => null,
                'email' => 'riker.simulation@makeadiff.in',
                'mad_email' => '',
                'phone' => '9987531687',
                'sex' => 'm',
                'password' => null,
                'password_hash' => '$2y$10$82LUwx6LtMu1sah6AQxyZOv2rt8s.bzbkRDaW4Nk.UFUKJIT7koWS',
                'auth_token' => null,
                'photo' => null,
                'joined_on' => '2019-10-08 11:08:29',
                'address' => '',
                'bio' => null,
                'facebook_id' => null,
                'verification_status' => null,
                'profile_progress' => 0,
                'source' => 'other',
                'source_other' => null,
                'birthday' => null,
                'job_status' => 'student',
                'edu_institution' => null,
                'company' => null,
                'preferred_day' => 'flexible',
                'applied_role' => null,
                'why_mad' => null,
                'left_on' => null,
                'added_on' => '0000-00-00 00:00:00',
                'updated_on' => '0000-00-00 00:00:00',
                'reason_for_leaving' => null,
                'induction_status' => '0',
                'teacher_training_status' => '0',
                'center_id' => null,
                'city_other' => null,
                'city_id' => 28,
                'subject_id' => 0,
                'project_id' => 1,
                'user_type' => 'volunteer',
                'credit' => 3.0,
                'consecutive_credit' => null,
                'admin_credit' => null,
                'campaign' => null,
                'zoho_user_id' => null,
                'status' => '1',
                'app_version' => null,
            ),
            5 =>
            array(
                'id' => 6,
                'name' => 'Sulu',
                'title' => null,
                'email' => 'sulu.simulation@makeadiff.in',
                'mad_email' => '',
                'phone' => '9987541587',
                'sex' => 'm',
                'password' => null,
                'password_hash' => '$2y$10$FwRoOc2JXVMHqkGHemmJJuPGHOt8Fqzs8sOr6gNqdLQnpeRmCyt56',
                'auth_token' => null,
                'photo' => null,
                'joined_on' => '2019-10-08 11:09:31',
                'address' => '',
                'bio' => null,
                'facebook_id' => null,
                'verification_status' => null,
                'profile_progress' => 0,
                'source' => 'other',
                'source_other' => null,
                'birthday' => null,
                'job_status' => 'student',
                'edu_institution' => null,
                'company' => null,
                'preferred_day' => 'flexible',
                'applied_role' => null,
                'why_mad' => null,
                'left_on' => null,
                'added_on' => '0000-00-00 00:00:00',
                'updated_on' => '0000-00-00 00:00:00',
                'reason_for_leaving' => null,
                'induction_status' => '0',
                'teacher_training_status' => '0',
                'center_id' => null,
                'city_other' => null,
                'city_id' => 28,
                'subject_id' => 0,
                'project_id' => 1,
                'user_type' => 'volunteer',
                'credit' => 3.0,
                'consecutive_credit' => null,
                'admin_credit' => null,
                'campaign' => null,
                'zoho_user_id' => null,
                'status' => '1',
                'app_version' => null,
            ),
        ));
    }
}
